{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\lazy_loader\\__init__.py:202: RuntimeWarning: subpackages can technically be lazily loaded, but it causes the package to be eagerly loaded even if it is already lazily loaded.So, you probably shouldn't use subpackages with this lazy feature.\n",
      "  warnings.warn(msg, RuntimeWarning)\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from uptrain import EvalLLM, Evals"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Load CSV with query, response, context, and ground truth\n",
    "data = pd.read_csv('llm_responses.csv')\n",
    "\n",
    "# Extract the necessary fields from the CSV\n",
    "queries = data['query']\n",
    "responses = data['response']\n",
    "contexts = data['context']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Initialize UpTrain EvalLLM instance\n",
    "eval_llm = EvalLLM(openai_api_key=\"\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m2024-10-15 17:46:11.547\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:01<00:00,  1.53s/it]\n",
      "c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\uptrain\\operators\\language\\llm.py:271: RuntimeWarning: coroutine 'LLMMulticlient.async_fetch_responses' was never awaited\n",
      "  with ThreadPoolExecutor(max_workers=1) as executor:\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "\u001b[32m2024-10-15 17:46:14.560\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:01<00:00,  1.90s/it]\n",
      "\u001b[32m2024-10-15 17:46:22.101\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 17:46:25.094\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:01<00:00,  1.96s/it]\n",
      "\u001b[32m2024-10-15 17:46:28.461\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:01<00:00,  1.79s/it]\n",
      "\u001b[32m2024-10-15 17:46:36.635\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 17:46:41.103\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:01<00:00,  1.82s/it]\n",
      "\u001b[32m2024-10-15 17:46:45.100\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:01<00:00,  2.00s/it]\n",
      "\u001b[32m2024-10-15 17:46:53.442\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 17:46:57.915\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:02<00:00,  2.12s/it]\n",
      "\u001b[32m2024-10-15 17:47:02.215\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:01<00:00,  1.93s/it]\n",
      "\u001b[32m2024-10-15 17:47:10.380\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 17:47:14.927\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:01<00:00,  1.88s/it]\n",
      "\u001b[32m2024-10-15 17:47:19.021\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:02<00:00,  2.09s/it]\n",
      "\u001b[32m2024-10-15 17:47:27.412\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 17:47:31.705\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:01<00:00,  1.64s/it]\n",
      "\u001b[32m2024-10-15 17:47:35.879\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:01<00:00,  1.31s/it]\n",
      "\u001b[32m2024-10-15 17:47:43.397\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 17:47:47.821\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:01<00:00,  1.77s/it]\n",
      "\u001b[32m2024-10-15 17:47:51.753\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:01<00:00,  1.41s/it]\n",
      "\u001b[32m2024-10-15 17:47:59.424\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 17:48:03.767\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "  0%|          | 0/1 [00:00<?, ?it/s]Task exception was never retrieved\n",
      "future: <Task finished name='Task-89' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-90' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-92' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-94' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-95' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-97' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-98' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-100' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-101' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "100%|██████████| 1/1 [00:02<00:00,  2.21s/it]\n",
      "\u001b[32m2024-10-15 17:48:08.147\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:01<00:00,  1.93s/it]\n",
      "\u001b[32m2024-10-15 17:48:16.312\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 17:48:20.658\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:02<00:00,  2.21s/it]\n",
      "\u001b[32m2024-10-15 17:48:25.015\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:02<00:00,  2.15s/it]\n",
      "\u001b[32m2024-10-15 17:48:33.412\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 17:48:37.673\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:01<00:00,  1.92s/it]\n",
      "\u001b[32m2024-10-15 17:48:41.734\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:01<00:00,  1.71s/it]\n",
      "\u001b[32m2024-10-15 17:48:49.685\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Evaluation for relevance complete. Results saved to 'evaluation_results_relevance.csv'\n"
     ]
    }
   ],
   "source": [
    "# Evaluate response relevance metric and save the findings\n",
    "metric_name = 'relevance'\n",
    "metric = Evals.RESPONSE_RELEVANCE\n",
    "\n",
    "results = []\n",
    "for query, response in zip(queries, responses):\n",
    "    metrics_result = {\n",
    "        'query': query,\n",
    "        'response': response\n",
    "    }\n",
    "\n",
    "    # Prepare data for evaluation\n",
    "    data_for_eval = [{\n",
    "        \"question\": query,\n",
    "        \"response\": response\n",
    "    }]\n",
    "\n",
    "    # Evaluate the metric\n",
    "    res = eval_llm.evaluate(data=data_for_eval, checks=[metric])\n",
    "    metrics_result[metric_name] = res[0].get('score_response_relevance', 'N/A')\n",
    "    metrics_result[f'{metric_name}_explanation'] = res[0].get('explanation_response_relevance', 'No explanation provided')\n",
    "\n",
    "    results.append(metrics_result)\n",
    "\n",
    "# Convert results to DataFrame and save to CSV\n",
    "results_df = pd.DataFrame(results)\n",
    "results_df.to_csv(f'evaluation_results_{metric_name}.csv', index=False)\n",
    "\n",
    "print(f\"Evaluation for {metric_name} complete. Results saved to 'evaluation_results_{metric_name}.csv'\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m2024-10-15 18:04:02.526\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:04<00:00,  4.42s/it]\n",
      "c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\uptrain\\operators\\language\\llm.py:271: RuntimeWarning: coroutine 'LLMMulticlient.async_fetch_responses' was never awaited\n",
      "  with ThreadPoolExecutor(max_workers=1) as executor:\n",
      "RuntimeWarning: Enable tracemalloc to get the object allocation traceback\n",
      "\u001b[32m2024-10-15 18:04:12.502\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 18:04:14.039\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:04<00:00,  4.22s/it]\n",
      "\u001b[32m2024-10-15 18:04:23.810\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 18:04:25.253\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:04<00:00,  4.82s/it]\n",
      "\u001b[32m2024-10-15 18:04:35.701\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 18:04:37.249\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:03<00:00,  3.47s/it]\n",
      "\u001b[32m2024-10-15 18:04:46.273\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 18:04:47.740\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "  0%|          | 0/1 [00:00<?, ?it/s]Task exception was never retrieved\n",
      "future: <Task finished name='Task-151' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-153' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-154' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-155' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-156' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-157' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-158' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-159' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "Task exception was never retrieved\n",
      "future: <Task finished name='Task-160' coro=<AsyncClient.aclose() done, defined at c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py:2024> exception=RuntimeError('Event loop is closed')>\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_client.py\", line 2031, in aclose\n",
      "    await self._transport.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpx\\_transports\\default.py\", line 389, in aclose\n",
      "    await self._pool.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 313, in aclose\n",
      "    await self._close_connections(closing_connections)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection_pool.py\", line 305, in _close_connections\n",
      "    await connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\connection.py\", line 171, in aclose\n",
      "    await self._connection.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_async\\http11.py\", line 265, in aclose\n",
      "    await self._network_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\httpcore\\_backends\\anyio.py\", line 55, in aclose\n",
      "    await self._stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\streams\\tls.py\", line 201, in aclose\n",
      "    await self.transport_stream.aclose()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\anyio\\_backends\\_asyncio.py\", line 1208, in aclose\n",
      "    self._transport.close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 1210, in close\n",
      "    super().close()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\selector_events.py\", line 875, in close\n",
      "    self._loop.call_soon(self._call_connection_lost, None)\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 795, in call_soon\n",
      "    self._check_closed()\n",
      "  File \"c:\\Users\\Emumba\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py\", line 541, in _check_closed\n",
      "    raise RuntimeError('Event loop is closed')\n",
      "RuntimeError: Event loop is closed\n",
      "100%|██████████| 1/1 [00:03<00:00,  3.05s/it]\n",
      "\u001b[32m2024-10-15 18:04:56.363\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 18:04:57.761\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:03<00:00,  3.43s/it]\n",
      "\u001b[32m2024-10-15 18:05:06.735\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 18:05:08.243\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:04<00:00,  4.22s/it]\n",
      "\u001b[32m2024-10-15 18:05:17.869\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 18:05:19.290\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:05<00:00,  5.16s/it]\n",
      "\u001b[32m2024-10-15 18:05:29.887\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 18:05:31.319\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:04<00:00,  4.91s/it]\n",
      "\u001b[32m2024-10-15 18:05:41.666\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n",
      "\u001b[32m2024-10-15 18:05:43.086\u001b[0m | \u001b[33m\u001b[1mWARNING \u001b[0m | \u001b[36muptrain.operators.language.llm\u001b[0m:\u001b[36mfetch_responses\u001b[0m:\u001b[36m268\u001b[0m - \u001b[33m\u001b[1mDetected a running event loop, scheduling requests in a separate thread.\u001b[0m\n",
      "100%|██████████| 1/1 [00:04<00:00,  4.56s/it]\n",
      "\u001b[32m2024-10-15 18:05:53.170\u001b[0m | \u001b[1mINFO    \u001b[0m | \u001b[36muptrain.framework.evalllm\u001b[0m:\u001b[36mevaluate\u001b[0m:\u001b[36m376\u001b[0m - \u001b[1mLocal server not running, start the server to log data and visualize in the dashboard!\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Evaluation for consistency complete. Results saved to 'evaluation_results_consistency.csv'\n"
     ]
    }
   ],
   "source": [
    "# Evaluate response consistency metric and save the findings\n",
    "metric_name = 'consistency'\n",
    "metric = Evals.RESPONSE_CONSISTENCY\n",
    "\n",
    "results = []\n",
    "for query, response, context in zip(queries, responses, contexts):\n",
    "    metrics_result = {\n",
    "        'query': query,\n",
    "        'contexts': context,\n",
    "        'response': response\n",
    "    }\n",
    "\n",
    "    # Prepare data for evaluation\n",
    "    data_for_eval = [{\n",
    "        \"question\": query,\n",
    "        \"context\": context,\n",
    "        \"response\": response\n",
    "    }]\n",
    "\n",
    "    # Evaluate the metric\n",
    "    res = eval_llm.evaluate(data=data_for_eval, checks=[metric])\n",
    "    metrics_result[metric_name] = res[0].get('score_response_consistency', 'N/A')\n",
    "    metrics_result[f'{metric_name}_explanation'] = res[0].get('explanation_response_consistency', 'No explanation provided')\n",
    "\n",
    "    results.append(metrics_result)\n",
    "\n",
    "# Convert results to DataFrame and save to CSV\n",
    "results_df = pd.DataFrame(results)\n",
    "results_df.to_csv(f'evaluation_results_{metric_name}.csv', index=False)\n",
    "\n",
    "print(f\"Evaluation for {metric_name} complete. Results saved to 'evaluation_results_{metric_name}.csv'\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
